### ISSUE TITLE
Determine how MacOS and other "Directory" artifact definitions are intended to be used

### ISSUE THREAD

**Issue by tomchop** [ForensicArtifacts/artifacts#285] opened 2018-08-24 12:26 UTC
The `MacOSApplications` artifact definition [1] is pretty broad, siphoning everything under `/Applications/`. We may want to reconsider how it is defined, or at least implement a way for the artifact to signal that its output may be very large.

[1] https://github.com/ForensicArtifacts/artifacts/blob/66611349a090f1a0639b2774e53fd4b404fb9770/data/macos.yaml#L14-L23

**Comment by joachimmetz** [comment] 2022-03-12 09:29
There are a couple of things with this artifact definition

* has been rename to MacOSApplicationsDirectory https://github.com/ForensicArtifacts/artifacts/blob/main/data/macos.yaml#L14
* DIRECTORY source type has been changed to PATH source type

@tomchop do you know how this artifact is currently used / was intended to be used ? What I can imaging is that intent was to get a listing of the sub directories.

**Comment by tomchop** [comment] 2022-03-14 13:44
4 years is a long time and I can't remember what I ran into when I opened this, but I suspect the main problem was that it returned too many entries.

**Comment by joachimmetz** [comment] 2022-03-14 15:02
Per chat, closing this issue. If more information about use cases unearths let's add them to this issue.

**Closed by joachimmetz** 2022-03-14 15:02 UTC
Labels: question
